#SVD
SVD also known as Singular Value Decomposition of a matrix is a factorization of that matrix into three matrices. It has some interesting algebraic properties and conveys important geometrical and theoretical insights about linear transformations. It also has some important applications in data science. In this article, I will try to explain the mathematical intuition behind SVD and its geometrical meaning.

Mathematics behind SVD The SVD of mxn matrix A is given by the formula :

A = UWV<sup>T</sup>

where, 
U: mxn matrix of the orthonormal eigenvectors of AA<sup>T</sup> . 

V_t: transpose of a nxn matrix containing the orthonormal eigenvectors of A<sup>T</sup>.A. 

W: a nxn diagonal matrix of the singular values which are the square roots of the eigenvalues of A<sup>T</sup>.A 

In [1]:
#import all the necessary header files inorder to perform SVD operation
import numpy as np
from scipy.linalg import svd

In [3]:
"""Singular Value Deposition """

A = np.array([[3,4,5],[5,6,7]])
print(A)

[[3 4 5]
 [5 6 7]]


In [14]:
#performing SVD operation on matrix A
u, W, V_t = svd(A)
print("U : \n", u)
print("\nSingular Matrix : \n", W)
print("\nV_t : \n",V_t)


U : 
 [[-0.55870157 -0.82936877]
 [-0.82936877  0.55870157]]

Singular Matrix : 
 [12.64317441  0.38748018]

V_t : 
 [[-0.46056064 -0.57034876 -0.68013688]
 [ 0.78817335  0.08964162 -0.6088901 ]
 [ 0.40824829 -0.81649658  0.40824829]]
